version: '3'

services:
  app:
    image: go-redis-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    network_mode: "host"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
